version: "3"

services:

  db:
    image: mysql:8.0.13
    volumes:
        - db-data:/var/lib/mysql/
    networks:
      - backend
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD

  webserver:
    image: nginx
    networks: 
      - backend
    ports:
      - "8080:80"
    depends_on:
      - app
    volumes:
      - ./nginx/localhost-dev:/etc/nginx/conf.d/mysite.template
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"

  app:
    build: .
    ports:
      - "3000:3000"
    command: "npm start"
    networks:
      - backend
    depends_on:
      - db

networks:
  backend:

volumes:
  db-data: