version: "3"

services:

  db:
    image: mysql:8.0.13
    volumes:
        - db-data:/var/lib/mysql/
    networks:
      - backend
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD


  app:
    build: .
    ports:
      - "3000:3000"
    command: "npm start"
    networks:
      - backend
    depends_on:
      - db
    environment:
      - DEBUG=weddingpage:*

networks:
  backend:

volumes:
  db-data: